# Versión utilizada
version: '3'

# Configuración de los servidores que vamos a necesitar
services: 
 
  # Contenedor para el servicio mysql

  # Se utilizará la carpeta 'database' como volumen para la persistencia de los datos de la BD
  mysql:
    image: mysql:5.7
    container_name: wordpress_db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dwes
      MYSQL_PASSWORD: dwes
      MYSQL_DATABASE: dwesdb

    volumes:
      - ./database:/var/lib/mysql


  # Servicio WordPress

  # Se utilizará la carpeta 'wordpress' como volumen para la persistencia de los datos de la la instalación

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    depends_on:
      - mysql
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: dwes
      WORDPRESS_DB_PASSWORD: dwes
      WORDPRESS_DB_NAME: dwesdb
    volumes:
      - ./wordpress:/var/www/html

  # Servicio phpmyadmin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wordpress_phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8080:80
    depends_on:
      - mysql